import { jsPDF } from 'jspdf';

export default function GeneratePDFButton({ list, items }) {
  const generatePDF = () => {
    const doc = new jsPDF();

    // Set background color (light cream for a warm, professional look)
    doc.setFillColor(255, 248, 231); // Softer cream for better contrast
    doc.rect(0, 0, 210, 297, 'F'); // A4 dimensions in mm

    // Header: Centered Title with Green Background
    doc.setFillColor(52, 168, 83); // Green background (#34A853)
    doc.rect(0, 0, 210, 20, 'F'); // Header rectangle (increased height for better balance)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255); // White text
    const title = `${list.title.toUpperCase()}`; // Title in uppercase
    const titleWidth = doc.getTextWidth(title); // Calculate title width
    const pageWidth = 210; // A4 width in mm
    const titleX = (pageWidth - titleWidth) / 2; // Center the title
    doc.text(title, titleX, 14); // Centered title

    // Group items by category
    const categories = {
      Bakery: [],
      Fruits: [],
      Meat: [],
      Other: [],
      Vegetables: [],
    };

    items.forEach(item => {
      if (categories[item.category]) {
        categories[item.category].push(item);
      } else {
        categories.Other.push(item); // Fallback for uncategorized items
      }
    });

    // Body: Improved layout with better spacing and hierarchy
    let y = 30; // Starting Y position after header
    doc.setTextColor(33, 33, 33); // Dark gray for better readability (#212121)
    doc.setFont('helvetica', 'normal');

    // Iterate through each category
    Object.keys(categories).forEach(category => {
      if (categories[category].length > 0) {
        // Category header
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(52, 168, 83); // Green for category headers
        doc.text(category.toUpperCase(), 15, y); // Left-aligned category
        y += 8; // Space after category header

        // Items in the category
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(33, 33, 33); // Dark gray for items
        categories[category].forEach(item => {
          // Checkbox square (unchecked)
          doc.setDrawColor(150, 150, 150); // Gray border for checkbox
          doc.setLineWidth(0.3);
          doc.rect(15, y - 3, 4, 4); // Small square for checkbox
          // Item text with quantity and quantity type
          doc.text(`${item.name} (${item.quantity} ${item.quantityType})`, 23, y); // Adjusted alignment
          y += 7; // Space between items
        });
        y += 5; // Extra space between categories
      }
    });

    // Footer: Modern and subtle
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120); // Lighter gray for footer
    doc.setFont('helvetica', 'italic');
    const footerText = 'Generated by HomeStocks';
    const footerWidth = doc.getTextWidth(footerText);
    const footerX = (pageWidth - footerWidth) / 2; // Center the footer
    doc.text(footerText, footerX, 287); // Centered footer near bottom

    // Add a subtle line above the footer for separation
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.2);
    doc.line(15, 282, 195, 282); // Horizontal line above footer

    // Save the PDF
    doc.save(`${list.title}-grocery-list.pdf`);
  };

  return (
    <button 
      onClick={generatePDF} 
      className="bg-green-800 text-white px-4 py-2 rounded-md hover:bg-green-700"
    >
      Download PDF
    </button>
  );
}