import { jsPDF } from "jspdf";

export const generateGroceryPDF = (items, checkedItems) => {
  const doc = new jsPDF();
  
  // Set document properties
  doc.setProperties({
    title: 'Grocery List',
    subject: 'Grocery Shopping List',
    author: 'HomeStocks',
    keywords: 'grocery, shopping, list',
    creator: 'HomeStocks'
  });

  // Set beige background for the entire document
  doc.setFillColor(245, 245, 220);
  doc.rect(0, 0, doc.internal.pageSize.width, doc.internal.pageSize.height, 'F');
  
  // Title with green box and white text
  doc.setFillColor(0, 128, 0);
  doc.rect(20, 10, 170, 15, 'F');
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text("GROCERY LIST", 105, 20, { align: 'center' });
  
  // Group items by category
  const categories = {};
  items.forEach(item => {
    if (!categories[item.category]) {
      categories[item.category] = [];
    }
    categories[item.category].push(item);
  });
  
  let yPos = 35;
  const sortedCategories = Object.keys(categories).sort();
  
  sortedCategories.forEach(category => {
    // Category header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 128, 0);
    doc.text(category.toUpperCase(), 20, yPos);
    
    yPos += 10;
    
    // Items list
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    
    const sortedItems = categories[category].sort((a, b) => a.name.localeCompare(b.name));
    
    sortedItems.forEach((item) => {
      // Draw checkbox
      doc.setDrawColor(0, 0, 0);
      doc.rect(25, yPos - 4, 5, 5);
      if (checkedItems[item._id]) {
        doc.line(25, yPos - 2, 27, yPos);
        doc.line(27, yPos, 30, yPos - 4);
      }
      
      doc.text(`${item.name}${item.quantity ? ` (${item.quantity})` : ''}`, 35, yPos);
      yPos += 7;
    });
    
    yPos += 10;
    
    if (yPos > 270) {
      doc.addPage();
      doc.setFillColor(245, 245, 220);
      doc.rect(0, 0, doc.internal.pageSize.width, doc.internal.pageSize.height, 'F');
      yPos = 20;
    }
  });
  
  // Footer
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by HomeStocks', 105, 285, { align: 'center' });
  
  return doc;
};